### ISSUE TITLE
Contract Module

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#26]
Custom Documentation:

- [x] The purpose of the module
- [ ] Explanation of the real world users and their role/interactions with the module
- [x] Key logic, processes, or assumptions that happen within the module
- [ ] Details on how a module easily integrates with other associated modules

Rust Docs:

- [ ] Available storage items and what they hold
- [x] Public Functions
- [x] Internal Functions

**Comment by nczhu** [comment]
Pull request in: 
https://github.com/paritytech/substrate/pull/2045 

Could use more examples though
