### ISSUE TITLE
System Module

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#39]
Custom Documentation:

- [ ] The purpose of the module
- [ ] Explanation of the real world users and their role/interactions with the module
- [ ] Key logic, processes, or assumptions that happen within the module
- [ ] Details on how a module easily integrates with other associated modules

Rust Docs:

- [ ] Available storage items and what they hold
- [ ] Public Functions
- [ ] Internal Functions

**Comment by gautamdhameja** [comment]
PR https://github.com/paritytech/substrate/pull/1999 merged. Closing this issue.
