### ISSUE TITLE
Treasury Module

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#41]
Custom Documentation:

- [ ] The purpose of the module
- [ ] Explanation of the real world users and their role/interactions with the module
- [ ] Key logic, processes, or assumptions that happen within the module
- [ ] Details on how a module easily integrates with other associated modules

Rust Docs:

- [ ] Available storage items and what they hold
- [ ] Public Functions
- [ ] Internal Functions

**Comment by nczhu** [comment]
IN progress: https://hackmd.io/s/Bku3OFyF4

**Comment by nczhu** [comment]
Needs content review. Does anyone know who might be familiar with the original intent behind this module? It seems to be a work in progress. 

https://hackmd.io/s/Bku3OFyF4

**Comment by shawntabrizi** [comment]
@nczhu I went down a hole that had me look into this module too... I agree it is weird. We should start a conversation with @gavofyork to better understand

**Comment by nczhu** [comment]
Found this snippet yesterday, which indicates the original purpose.
Neat module - will write a sample for this! 

> Treasury
> The system needs to continually raise funds, which we call the treasury. These funds are used to pay for developers that provide software updates, apply any changes decided by referenda, adjust parameters, and generally keep the system running smoothly.
> 
> Funds for treasury are raised in two ways:
> 
> by minting new tokens, leading to inflation, and
> by channelling some of the tokens set for burning from transaction fees and slashing.
> Notice that these methods to raise funds mimic the traditional ways that governements raise funds: by minting coins which leads to controlled inflation, and by collecting taxes and fines.
> 
> We could raise funds solely from minting new tokens, but we argue that it makes sense to redirect some of the stake set for burning into treasury:
> 
> By doing so we reduce the amount of actual stake burning, and this gives us better control over the inflation rate (notice that stake burning leads to deflation, and we can’t control or predict the events that lead to burning).
> Suppose that there is a period in which there is an unusually high amount of stake burning, due to either misconducts or transaction fees. This fact is a symptom that there is something wrong with the system, that needs fixing. Hence, this will be precisely a period when we need to have more funds available in treasury to afford the development costs to fix the problem.
