### ISSUE TITLE
SRML Documentation Template

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#44]
We need to create a markdown template for SRML documentation

**Comment by shawntabrizi** [comment]
From @joepetrowski 

Docs Template
=

## Overview

Short paragraph about the purpose of the module.

### Terminology

Concepts, storage items, or actions that you think deserve to be noted to give context to the rest of the documentation or module usage. 

The author needs to use some judgment about what is included. We don't want a list of every storage item nor types - the user can go to the code for that. For example, "transfer fee" is obvious and should not be included, but "free balance" and "reserved balance" should be noted to give context to the module.

## Public Interface

### Types

Any associated types and where the user would typically define them.

### Dispatchable Functions

A brief description of dispatchable functions and a link to the rustdoc with their actual documentation.

### Public Functions

A link to the rustdoc and any notes about usage in the module, not for specific functions. For example, in the balances module: "Note that when using the publicly exposed functions, you (the runtime developer) are responsible for implementing any necessary checks (e.g. that the sender is the signer) before calling a function that will affect storage."

## Usage

2-3 examples of usage.

- 1 simple, e.g. calling a getter
- 1 usage in an actual runtime example (see TCR or Kitties)

## Dependencies

Dependencies on other modules and genesis config, if applicable.

## References

Links to reference material, if applicable. For example, Phragmen, W3F research, etc. that the implementation is based on.

**Comment by AmarRSingh** [comment]
## Overview

## Interface

### Types

### Dispatchable
full list with origin

### Public
> up to writer for respective module (wrt how much information to provide)

## Usage

### Prerequisites

### Simple Code Snippet

### Example from SRML

## Genesis Config

## Related Modules
> bulleted list to other modules (maybe one sentence)

## References

**Comment by shawntabrizi** [comment]
Template is tentatively finalized.

**Comment by ltfschoen** [comment]
FYI, note that I'm in the process of incorporating this template into https://github.com/paritytech/substrate/pull/1947
