### ISSUE TITLE
Add link to parity-samples repo

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/substrate-developer-hub#5]

**Comment by JoshOrndorff** [comment]
@bjornwgnr Were you referring to the parity sample github organization? I thought it lived here https://github.com/parity-samples

But it seems maybe it is gone? It looks like the repositories moved over here (notice this redirect https://github.com/parity-samples/substrate-erc20-multi).

So I'm going to close this issue. Reopen if I misunderstood, or if you want a more specific thing.
