### ISSUE TITLE
Update all documentation to use `decl_dispatch`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#50]
Substrate has renamed the `decl_module` macro to `decl_dispatch`:
https://github.com/paritytech/substrate/issues/1960

We need to update all documentation accordingly.

**Comment by gautamdhameja** [comment]
It seems this rename is not happening - 
https://github.com/paritytech/substrate-developer-hub/issues/58#issuecomment-476421703. 
https://github.com/paritytech/substrate/issues/1960#issuecomment-476402438
Closing this issue.
