### ISSUE TITLE
Community Building Initiatives

### ISSUE THREAD

**Issue by 4meta5** [paritytech/substrate-developer-hub#57]
As the codebase stabilizes, we need to start building a community around Substrate.

## Substrate Newsletter

* Weekly or biweekly newsletter highlighting open source projects that are being built with Substrate, related virtual and physical hackathons (see section below), conferences, and ongoing initiatives (virtual office hours, etc). 

* I think I'm plugged into the teams that are building with Substrate so I could help with this; I've collected some of the repos [here](https://github.com/AmarRSingh/Parity/blob/master/Substrate/dessert.md), but I'm sure there are many more that I'm unaware of!

* I don't have much experience with this, but I have friends who have recommended using some combination of the following to manage newsletters: `Airtable` + `Zapier` + `Mailchimp`

## (Virtual) Hackathons

* virtual hackathons that take place over longer time periods (multiple weeks) are increasing in popularity (recent example is the [NuCypher + Coinlist Hackathon](https://coinlist.co/build/nucypher))

* **Substrate has a higher learning curve than other blockchain frameworks** so I think this format is actually more conducive to encouraging development vs the conventional 1-2 day physical hackathons

* **Cosmos** has had a lot of success with virtual hackathons. In fact, some of the most active Cosmos Golang developers were hired after they won virtual hackathons (ie [cwgoes](https://github.com/cwgoes), [mossid](https://github.com/mossid)).

* an ongoing competition like the [Solidity Gas Golf competition](https://g.solidity.cc/) but for DApp functionalities would be smart to emphasize the necessity of being conservative with storage usage and computation

## Weekly Office Hours

* `Full Node`, `Factory` or **virtual**

* by specifying a slot every week that we're available for questions, it might encourage people to spend more time working with the platform beforehand so that they can ask questions during the specified time (vs just telling people to ask in the Riot channels whenever a question arises)

**Comment by a13xndra** [comment]
Lots of great ideas @AmarRSingh! 

Some questions come to my mind when deciding which community-building endeavors to pursue and how to pursue them: 
- What is our goal with building a community around Substrate?
- Is our goal to get people to build chains and connect them to Polkadot? If so, do we want specific chains built? If so, should we orient hackathons around those? 
- Is our goal to just have as many people as possible building with Substrate with the vision that Polkadot will one day be able to support them all? 
- Who is our target audience? Is it Ethereum DApp developers, large organizations looking to build a blockchain, existing DApps that want the advantages of having their own chain, and/or developers who can work in the Substrate ecosystem? 
- How do we point DApp developers who should be building with smart contracts to build on smart contracts? 
- Do we also want to be building a developer community around Edgeware? 

# Substrate Newsletter
Right now we're sending out a monthly Parity newsletter with Activecampaign. We could create a separate Substrate list in Activecampaign. For a Substrate dedicated newsletter, I wonder: 
- Where would people go to sign up for it? 
- How would we promote the newsletter? The Parity email list has been slow to grow and we are promoting that everywhere on parity.io. 
- Is there someone who can take ownership for creating and sending newsletter content?
- Should the newsletter focus on both Substrate and Polkadot? Right now Polkadot has its own separate newsletter. 

I've also been wanting to collect profiles of projects building on Substrate and put those on the blog, but I seem to not be finding the time. I have also been meaning to do a better job tweeting announcements about projects building on Substrate, as well as putting them on r/dot and r/substrate. 

# (Virtual) Hackathons
I agree that a multiple-week virtual hackathon will probably be much more successful than an in-person event. My sense of timing was that we were waiting for the code base to stabilize a little and we also wanted to see how Sub0 goes and then plan this out, but the earlier we start planning the better. Some questions that come to mind on this: 
- Do we want to start first with online workshops? 
- Is there someone who can take ownership for coordinating the virtual hackathons?
- What would our goal be for the hackathon? Are we looking to encourage teams to build specific chains for Polkadot? 
- There are a lot of options for teaming up with different hackathon groups to expand our reach. I believe @kafabisch was evaluating the different options. 

# Weekly office hours
I'd love to see this happen virtually. 
- Is there someone available for these office hours?

**Comment by nczhu** [comment]
These are all great ideas! 

Some random thoughts building on them: 

i) Maybe the newsletter can be redistributed through various channels: reddit, public forum, etc. I'm getting teh sense that folks in this space use email less and less :) 

ii) `collect profiles of projects building on Substrate and put those on the blog` @a13xndra , I'll help with this! Researching teams and collating questions for those teams now.

Iii) One thing that could combine what we're trying to achieve through newsletters/weekly office hours could be a recurring community call. Featuring announcements, small (remote) workshops, project sharing by an eng. 

I've attended some hosted by MakerDao - they are great, esp for international outreach. Occasionally they'll bring on a dev to talk about a specific subject, and the casual feel of these calls encourage A LOT of relevant questions.

It is time consuming / not super scalable in the beginning - but if anyone is interested, I'd love to pair with someone on this and get it going!

**Comment by JoshOrndorff** [comment]
This issue is getting stale, So I'm going to summarize and close. If the discussion should keep goingm, I propose opening a separate issue for the individual community building initiative.

I'm taking ownership of office hours. We're starting bi-weekly for now. https://www.reddit.com/r/substrate/comments/bukfoc/substrate_collaborative_learning_monday_03_june/

 Virtual Hackathons are starting to take share in the form of Rob's coding sessions and my office hours. If we want more coverage in the future, let's reconsider in a specific issue.

Sounds like the existing parity and polkadot newsletters are doing a sufficient job covering substrate considering that nobody volunteered to start a new one right now.

Please re-open if I'm closing prematurely.
