### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-developer-hub#59]
Create a style guide for consistent documentation.

For example, `my_function` vs `my_function()`.

**Comment by shawntabrizi** [comment]
Some questions I would want answered:
[ ] Using `!` for `my_macro_name!`
[ ] Periods at the end of bullet lists
[ ] Full sentences/periods for inline code comments
[ ] Hardlinks vs relative links
[ ] UK vs US English
[ ] Capitalization of terms (module names, Substrate, etc...)

probably more, hopefully other will add to the list

**Comment by shawntabrizi** [comment]
Should style guide also contain some documentation philosophy?

i.e. different kinds of docs:
* Reference Documentation
* Tutorials
* High Level Concepts
* etc...

"Precise, Concise, and Accurate"

etc...

**Comment by joepetrowski** [comment]
I don't think this should include frameworks for different kinds of docs. The idea is that reading docs from Parity should have a similar feel, but not to define what each type of doc includes.

UK vs US English is hard, because there is no definition of either one. (As in, France actually has a state-run language academy). For "US English" there is AP style guide, Chicago manual of style, Strunk & White... However, I will list common inconsistencies and mistakes that I see.

Anyway, will get a version out today and we can discuss what's missing.

**Comment by folsen** [comment]
For function names, macros etc we should look to how Rust does it, it's deep enough that we should have some consistency with other Rust docs, assuming people have some familiarity with that already (or will have through reading the rust book first and things like that)

**Comment by shawntabrizi** [comment]
@joepetrowski on Riot, I think we agreed to use US English before 1.0 release, which prompted me to make this issue: https://github.com/paritytech/substrate/issues/1768
