### ISSUE TITLE
construct_runtime docs need an update

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-developer-hub#82]
https://github.com/paritytech/substrate/blob/master/srml/support/src/runtime.rs#L22

Still a TODO in there and could use review.

**Comment by thiolliere** [comment]
hmm I actually don't know the difference between Block and NodeBlock.

maybe @bkchr ?

**Comment by bkchr** [comment]
`Block` is the block type that is used in the runtime and `NodeBlock` is the block type that is used in the node. They for example differ in the extrinsics type.

**Comment by thiolliere** [comment]
fixed by https://github.com/paritytech/substrate/pull/2552
