### ISSUE TITLE
decl_storage

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-developer-hub#9]

**Comment by thiolliere** [comment]
could be an inspiration https://github.com/paritytech/wiki/blob/0ba25fb9586bd38c471adf9aefaa6fcb096fabe5/decl_storage.md

**Comment by ltfschoen** [comment]
> could be an inspiration https://github.com/paritytech/wiki/blob/0ba25fb9586bd38c471adf9aefaa6fcb096fabe5/decl_storage.md

yes its currently published https://wiki.parity.io/decl_storage

**Comment by shawntabrizi** [comment]
@thiolliere Should we close this?

**Comment by thiolliere** [comment]
The doc doesn't mentionned metadata though.

And I don't know how we should organize high level doc on macros, like description of trie storage in SRML.

the rustdoc mentionned is in my opinion quite complete for using it

**Comment by bkchr** [comment]
I would like to have some documentation that compiles and is run by doc tests in rust. So, we are actually sure that the documentation does not break. 
Further I would add real code an no example code that shows the syntax we accept. Showing real code, makes it much faster understandable, especially if you are not familiar with macros.

**Comment by shawntabrizi** [comment]
That is a great suggestion, and it seems we need to take advantage of [this feature](https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example) to do that effectively in our docs.
